version: "3.9"

services:
  neo4j:
    image: neo4j:5.22
    container_name: bible_neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/password}
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_PLUGINS=[]
      - NEO4J_dbms_allow__upgrade=true
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./import:/var/lib/neo4j/import

volumes:
  neo4j_data:
  neo4j_logs:


